# Generated by Django 4.1.3 on 2022-11-11 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='liked_by',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='comments',
            name='cmt_likes',
            field=models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
